spring:
  profiles:
    active: local

---
spring:
  profiles: local
  freemarker:
    charset: UTF-8
    check-template-location: true
    enabled: true
    suffix: .ftl
    template-loader-path: classpath:/templates
  r2dbc:
    url: r2dbc:pool:postgresql://127.0.0.1:5432/basquiat
    username: postgres
    password: basquiat
    pool:
      initial-size: 10
      max-size: 30
      max-idle-time: 30m
      validation-query: SELECT 1
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        min-idle: 2
        max-idle: 5
        max-active: 10

springfox:
  documentation:
    swagger-ui:
      base-url: /documentation

logging:
  level:
    org.springframework.data.r2dbc: DEBUG